### PR TITLE
implement methods for pagination

### PR DESCRIPTION
**Pull request by ryabrody**

### CODE REVIEW

**Comment by pape-io** [comment]
Will add documentation and backport to v1 and v2

**Comment by ryabrody** [comment]
It is not really sure anymore if we really need this. I have to check with Matthias (my Saga Boss) if we really wanna implement it 🙈. Sorry may you can wait with backporting it?

**Comment by skaestle** [comment]
:+1:

**Comment by Averethel** [comment]
LGTM :+1:

**Pull request merged**
