### PR TITLE
Improved inspect

### PR DESCRIPTION
**Pull request by pape-io**
Recently Active Record changed the way how Records are printed on the terminal (aka `inspect`), here an example:
```
=> #<Customer:0x007f9ee48537b8
 id: 18,
 user_input_customer_number: nil,
 name: "Büro Meier",
 language: "de",
 created_at: Thu, 28 Jul 2016 11:00:31 CEST +02:00,
 updated_at: Thu, 28 Jul 2016 11:00:32 CEST +02:00
```

They split the first level attributes by new lines. This PR is not only adapting printing Records more readable on the terminal, it also fixes printing Data (not assigned to any record, like nested data) properly on the terminal.

# Before
```
=> <Entry{:_class=>"PlaceLocalEntry", :customer=>{:name=>"Max", :phone=>"+41414141", :email=>"max@muster.ch", :claims=>[], :created_date=>"2013-06-24T11:32:58.190+02:00"}
```
# After
```
=> Entry#12345
:_class=>"PlaceLocalEntry", 
:customer=>{:name=>"Max", :phone=>"+41414141", 
:email=>"max@muster.ch", 
:claims=>[], 
:created_date=>"2013-06-24T11:32:58.190+02:00"
```

The same for Data.

### CODE REVIEW

**Comment by cedricwider** [comment]
👍

**Comment by Averethel** [comment]
Spec would be nice, otherwise 👍

**Comment by pape-io** [comment]
Will try https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/output-matcher

**Comment by pape-io** [comment]
@Averethel output matcher does not catch inspects! Will go with string comparison

**Pull request merged**
